log:
  service_name: api-server
  format: text
  level: info

server:
  pprof:
    enable: true
    port: 6060
  grpc:
    port: 5000
    log_payload: true
    health_check: true
    reflection: true

postgres:
  migrate: true
  debug: true
  writer:
    host: localhost
    port: 5432
    user: postgres
    password: 123456aA@
    database: base_project
    ssl_mode: disable
    max_idle_conns: 5
    max_open_conns: 10
    max_conn_idle_time: 5m
    max_conn_lifetime: 15m
  reader:
    enable: true
    host: localhost
    port: 5432
    user: postgres
    password: 123456aA@
    database: base_project
    ssl_mode: disable
    max_idle_conns: 5
    max_open_conns: 10
    max_conn_idle_time: 5m
    max_conn_lifetime: 15m

redis:
  address:
    - localhost:6379
  password: 123456aA@
  db: 0

#otel:
#  endpoint: localhost:4317
#  format: grpc

jwt:
  secret: super-secret-b7b75f32-690f-42ab-b5df-c2ce63c0fede
  token_expires: 5m
  refresh_expires: 24h

crypto:
  public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JR0pBb0dCQUpmc0ZJc09sTHJ3S29tMSt2WnAzTWVIaUkwR3lQc0hXeUVpMmg5RFIwU1czNHlzU1hRNXJoYTkKODZseFJMeVZDSWlEUk9jdVVNVnVUTW4ybldadnJIOHZCMFJUY3ZCRkkwRjhMTnJQQnVTZS9pQmFpTTNPckt6SQpJS05YRThtMHBxMmR6VmF1MDVuSEVGcktQTGN6Z2xDbDV6U0FHYk9VUXlMVHNTOXU0K2V2QWdNQkFBRT0KLS0tLS1FTkQgUlNBIFBVQkxJQyBLRVktLS0tLQ==
  private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNYN0JTTERwUzY4Q3FKdGZyMmFkekhoNGlOQnNqN0Ixc2hJdG9mUTBkRWx0K01yRWwwCk9hNFd2Zk9wY1VTOGxRaUlnMFRuTGxERmJreko5cDFtYjZ4L0x3ZEVVM0x3UlNOQmZDemF6d2JrbnY0Z1dvak4KenF5c3lDQ2pWeFBKdEthdG5jMVdydE9aeHhCYXlqeTNNNEpRcGVjMGdCbXpsRU1pMDdFdmJ1UG5yd0lEQVFBQgpBb0dCQUkyUGFya0VWaXcybTd5RU9Kd2htcHJGdk1TRUhRUmtIMU1xRVl0dCtsdDhKa1FEU2RLbDZJVENiT2huClpnQSs4cHVaamJ2STJYU09TYmtyTmhGOFg0TVhQUkxVR3FiZ2RkVUk4SVJFYmxHTjUvajlNanJ5QmVBRzN0eDcKTElRNDRwWG8xWVA4UVg1bHhRMUZUVm8wSWJMWG5TTkZSS3JmbUgzdktnd1dkR2NSQWtFQXo4d0lieTJwaFZocApzbmdUZ3lrSWxpaHdONyswRVlhRDJkTVdUaVFvS01PN1NJM0ovVEZlcE9sY1FiSW9naGxMVk14ZlRFYmxuUXlYCmovdXpIbklVU1FKQkFMc3A3OTcveFduZEVvWk5rVlhzM2dxbHozQU53UlpNbzUwK29DRTk4VHVTRDRJazN5aHcKdy9WMFB4WVc4d00xRFJ2UWtOWHY0NHkralFLRmh0ZTlMRGNDUUdHYk5Wc0QxOTBLNnBzcVRBQVFCamlDUmpQcAptR3VqQTh3Tm15eVpUMFBXck9JbnQvbDJkejUvWHhaODJRcERWMTg5b0lYengyYzl3dk9mQjBRRjBnRUNRQkJuCmJJNnUvQzU3SWRTRGwrbGdDVllGa2xqUDI4eUlpdzZOSHB2TFFnbG1rOVZrUmVyVmQxZGNDT3QydDNYZ2dIV2YKb2hJZUpHT0JqL3BZbWFqdSs2RUNRQmtFSm93eS82REpRb0NSbThYVWZSTzYxa0dOdE5RSkpzVEcvdnhPQ2hTMwplUlptcC9xazJnSFkrM1l0dVlLMk1DQ1VIcDJzM25iMDdLaTQ0bEtXWFFjPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
