// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/anhnmt/go-api-boilerplate/internal/service/user/transport/grpc"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func New(grpcSrv *grpc.Server) error {
	userServiceServer := usergrpc.New(grpcSrv)
	error2 := initServices(userServiceServer)
	return error2
}
